name: CI Pipeline for Running Two Bash Scripts and RISC-V

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-bash-scripts:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Install GCC (required for C compilation)
    - name: Install GCC
      run: sudo apt-get update && sudo apt-get install -y build-essential

    # Step 3: Ensure the scripts have execution permissions
    - name: Make Bash Scripts Executable
      run: |
        chmod +x 01.IO_flush/bash_script.sh
        chmod +x 02_MEM_OVERCOMMIT/over_commit.sh

    # Step 4: Run the Bash script from 01.IO_flush
    - name: Run Bash Script 1 (IO_flush)
      run: bash 01.IO_flush/bash_script.sh

    # Step 5: Upload Executable from 01.IO_flush as an Artifact
    - name: Upload Artifact 1
      uses: actions/upload-artifact@v3
      with:
        name: io_flush_executable
        path: 01.IO_flush/program  # Replace 'program' with the actual filename

    # Step 6: Run the Bash script from 02_MEM_OVERCOMMIT
    - name: Run Bash Script 2 (MEM_OVERCOMMIT)
      run: bash 02_MEM_OVERCOMMIT/over_commit.sh

    # Step 7: Upload Executable from 02_MEM_OVERCOMMIT as an Artifact
    - name: Upload Artifact 2
      uses: actions/upload-artifact@v3
      with:
        name: mem_overcommit_executable
        path: 02_MEM_OVERCOMMIT/overcommit  # Replace 'overcommit' with the actual filename

  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Ensure all files are readable
    - name: Set Read Permissions for All Files
      run: chmod +r 03.RISC-Z/*

    # Step 3: Install Prerequisites
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git flex bison libgmp-dev libmpc-dev libmpfr-dev texinfo

    # Step 4: Install CMake
    - name: Install CMake
      run: sudo apt-get install -y cmake

    # Step 5: Install QEMU
    - name: Install QEMU
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static
        sudo ln -s /usr/bin/qemu-riscv64-static /usr/bin/qemu-riscv64
    
    # Step 6: Verify QEMU Installation
    - name: Verify QEMU Installation
      run: qemu-riscv64 --version



    # Step 6: Clone and Build RISC-V Toolchain with Newlib
    - name: Build RISC-V Toolchain
      run: |
        git clone https://github.com/riscv-collab/riscv-gnu-toolchain.git
        cd riscv-gnu-toolchain
        ./configure --prefix=/opt/riscv --with-arch=rv64imac --with-abi=lp64
        make newlib -j$(nproc)

    # Step 7: Add RISC-V Toolchain to PATH
    - name: Add RISC-V Toolchain to PATH
      run: echo "PATH=/opt/riscv/bin:/usr/bin:/bin:\$PATH" >> $GITHUB_ENV

    # Step 8: Configure and Build the Project with CMake
    - name: Configure and Build with CMake
      run: |
        cd 03.RISC-Z
        mkdir -p build
        cd build
        cmake ..
        cmake --build .
      env:
        PATH: /opt/riscv/bin:/usr/bin:/bin:$PATH

    # Step 9: Run Unit Tests using QEMU
    - name: Run Unit Tests
      run: |
        cd 03.RISC-Z/build
        qemu-riscv64 ./tests
      env:
        PATH: /opt/riscv/bin:/usr/bin:/bin:$PATH
